/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-21 00:50:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class book_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/afterLoginNavbar.jsp", Long.valueOf(1713641801600L));
    _jspx_dependants.put("/links.jsp", Long.valueOf(1713637867517L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\r\n");
      out.write("  <title>Visa Booking Application</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("  <style>\r\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');\r\n");
      out.write("	</style>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light\" style=\"background-color: #003875;\"> <!-- Changed bg-light to custom background color -->\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"nav-link text-white\" href=\"index.jsp\"><img src=\"ucm.jpeg\" alt=\"Image\" style=\"height: 75px; width: 75px;\"></a>\r\n");
      out.write("    <a class=\"nav-link text-white me-5 p-3 fs-1 fw-bold\" href=\"about.jsp\">UCM Embassy and Immigrations</a>\r\n");
      out.write("    <div class=\"navbar-nav me-auto\">\r\n");
      out.write("      ");
      out.write("<head>\r\n");
      out.write("  <title>Visa Booking Application</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("  <style>\r\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');\r\n");
      out.write("	</style>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"navbar-nav\">\r\n");
      out.write("      <a class=\"nav-link text-white fs-3\" href=\"book.jsp\"> Book Slot </a> <!-- Added text-white class for white text -->\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"navbar-nav\">\r\n");
      out.write("          <a class=\"nav-link text-white fs-3\" href=\"viewBookings.jsp\"> View Bookings </a> <!-- Added text-white class for white text -->\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"navbar-nav\">\r\n");
      out.write("               <a class=\"nav-link text-white fs-3\" href=\"logout.jsp\">Logout </a> <!-- Added text-white class for white text -->\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("<head>\r\n");
      out.write("  <title>Visa Booking Application</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("  <style>\r\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');\r\n");
      out.write("	</style>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("           $( function() {\r\n");
      out.write("             $('#datepicker').datepicker({\r\n");
      out.write("                    dateFormat: 'yy-mm-dd',\r\n");
      out.write("                    minDate: new Date()\r\n");
      out.write("                });\r\n");
      out.write("           } );\r\n");
      out.write("\r\n");
      out.write("            $( function() {\r\n");
      out.write("                $('#entryDate').datepicker({\r\n");
      out.write("                       dateFormat: 'yy-mm-dd',\r\n");
      out.write("                       minDate: new Date()\r\n");
      out.write("                   });\r\n");
      out.write("            } );\r\n");
      out.write("\r\n");
      out.write("            $( function() {\r\n");
      out.write("                $('#dateOfBirth').datepicker({\r\n");
      out.write("                       dateFormat: 'yy-mm-dd'\r\n");
      out.write("                   });\r\n");
      out.write("            } );\r\n");
      out.write("   </script>\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: #f8f9fa;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container mt-5\">\r\n");
      out.write("    <h2>Visa Booking Form</h2>\r\n");
      out.write("    <form action=\"book\" method=\"get\">\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"fullName\">Full Name</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"fullName\" name=\"fullName\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"passportNumber\">Passport Number</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"passportNumber\" name=\"passportNumber\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"motherName\">Mother's Name</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"motherName\" name=\"motherName\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"fatherName\">Father's Name</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"fatherName\" name=\"fatherName\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"typeOfVisa\">Type of Visa</label>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("          <select class=\"form-control dropdown-toggle\" id=\"typeOfVisa\" name=\"typeOfVisa\" required>\r\n");
      out.write("            <option value=\"\">Select Visa Type</option>\r\n");
      out.write("            <option value=\"Tourist Visa\">Tourist Visa</option>\r\n");
      out.write("            <option value=\"Business Visa\">Business Visa</option>\r\n");
      out.write("            <option value=\"Student Visa\">Student Visa</option>\r\n");
      out.write("            <option value=\"Work Visa\">Work Visa</option>\r\n");
      out.write("            <option value=\"Transit Visa\">Transit Visa</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"dateOfAppointment\">Date of Appointment</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"datepicker\" name=\"dateOfAppointment\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"entryDate\">Entry Date</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control datepicker\" id=\"entryDate\" name=\"entryDate\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("          <label for=\"entryDate\">Date of Birth</label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control datepicker\" id=\"dateOfBirth\" name=\"dateOfBirth\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"venue\">Venue</label>\r\n");
      out.write("        <select class=\"form-control\" id=\"venue\" name=\"venue\" data-toggle=\"dropdown\" required>\r\n");
      out.write("          <option value=\"\">Select Venue</option>\r\n");
      out.write("          <option value=\"Hyderabad,India\">Hyderabad, India</option>\r\n");
      out.write("          <option value=\"Chennai,India\">Chennai, India</option>\r\n");
      out.write("          <option value=\"Mumbai,India\">Mumbai, India</option>\r\n");
      out.write("          <option value=\"London,UK\">London, UK</option>\r\n");
      out.write("          <option value=\"Paris,France\">Paris, France</option>\r\n");
      out.write("          <option value=\"Sydney,Australia\">Sydney, Australia</option>\r\n");
      out.write("          <option value=\"Dubai,UAE\">Dubai, UAE</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\" value=\"submit\">Submit</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
